//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AditivoContrato
    {
        public AditivoContrato()
        {
            this.ClausulaContratoes = new HashSet<ClausulaContrato>();
            this.ParametroContratoes = new HashSet<ParametroContrato>();
            this.Projetoes = new HashSet<Projeto>();
        }
    
        public long aditivoContratoId { get; set; }
        public string identificador { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public System.DateTime dataInicioVigencia { get; set; }
        public Nullable<System.DateTime> dataFimVigencia { get; set; }
        public Nullable<int> tempoDuracaoMeses { get; set; }
        public Nullable<decimal> valorEstimadoConsumo { get; set; }
        public string criterioConsumo { get; set; }
        public Nullable<bool> contemplaSLA { get; set; }
        public Nullable<long> contratoId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Contrato Contrato { get; set; }
        public virtual ICollection<ClausulaContrato> ClausulaContratoes { get; set; }
        public virtual ICollection<ParametroContrato> ParametroContratoes { get; set; }
        public virtual ICollection<Projeto> Projetoes { get; set; }
    }
}
