//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anexo
    {
        public long anexoId { get; set; }
        public int sequenciaAnexo { get; set; }
        public string nome { get; set; }
        public string nomeInterno { get; set; }
        public string caminho { get; set; }
        public Nullable<long> servicoId { get; set; }
        public Nullable<long> ordemId { get; set; }
        public Nullable<long> logOrdemServicoId { get; set; }
        public Nullable<long> parecerId { get; set; }
        public Nullable<System.DateTime> dataUpload { get; set; }
        public Nullable<int> anexo1 { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
        public Nullable<long> atividadeId { get; set; }
        public Nullable<long> logAtividadeId { get; set; }
    
        public virtual LogOrdemServico LogOrdemServico { get; set; }
        public virtual Ordem Ordem { get; set; }
        public virtual Parecer Parecer { get; set; }
        public virtual Servico Servico { get; set; }
    }
}
