//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Aplicativo
    {
        public Aplicativo()
        {
            this.AplicativoOrdems = new HashSet<AplicativoOrdem>();
            this.AplicativoServicoes = new HashSet<AplicativoServico>();
            this.Funcionalidades = new HashSet<Funcionalidade>();
        }
    
        public long aplicativoId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public string plataforma { get; set; }
        public string parametroGeral { get; set; }
        public Nullable<long> projetoId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Projeto Projeto { get; set; }
        public virtual ICollection<AplicativoOrdem> AplicativoOrdems { get; set; }
        public virtual ICollection<AplicativoServico> AplicativoServicoes { get; set; }
        public virtual ICollection<Funcionalidade> Funcionalidades { get; set; }
    }
}
