//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Cargoes = new HashSet<Cargo>();
            this.LogOrdemServicoes = new HashSet<LogOrdemServico>();
            this.Parecers = new HashSet<Parecer>();
        }
    
        public long areaId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public long empresaId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Cargo> Cargoes { get; set; }
        public virtual ICollection<LogOrdemServico> LogOrdemServicoes { get; set; }
        public virtual ICollection<Parecer> Parecers { get; set; }
    }
}
