//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadeExecucao
    {
        public long AtividadeExecucaoId { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<int> prioridade { get; set; }
        public Nullable<System.DateTime> dataExecucao { get; set; }
        public Nullable<long> AtividadeId { get; set; }
        public long StatusAtividadeExecucaoId { get; set; }
        public Nullable<long> usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public Nullable<System.DateTime> dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Atividade Atividade { get; set; }
        public virtual StatusAtividadeExecucao StatusAtividadeExecucao { get; set; }
    }
}
