//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividade
    {
        public Atividade()
        {
            this.Atividade1 = new HashSet<Atividade>();
            this.AtividadeExecucaos = new HashSet<AtividadeExecucao>();
            this.AtividadePrazoes = new HashSet<AtividadePrazo>();
            this.LogAtividades = new HashSet<LogAtividade>();
            this.RecursoEfetivoes = new HashSet<RecursoEfetivo>();
        }
    
        public long atividadeId { get; set; }
        public int sequenciaAtividade { get; set; }
        public string nome { get; set; }
        public string descricao { get; set; }
        public Nullable<int> prioridade { get; set; }
        public Nullable<System.DateTime> dataEstimadaInicio { get; set; }
        public Nullable<System.DateTime> dataEstimadaFim { get; set; }
        public Nullable<System.DateTime> dataEfetivaInicio { get; set; }
        public Nullable<System.DateTime> dataEfetivaFim { get; set; }
        public Nullable<long> subAtividadeRelacionada { get; set; }
        public long tipoAtividadeId { get; set; }
        public long servicoId { get; set; }
        public long statusAtividadeId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
        public Nullable<int> prazoEfetivo { get; set; }
        public Nullable<long> tecnologiaId { get; set; }
    
        public virtual ICollection<Atividade> Atividade1 { get; set; }
        public virtual Atividade Atividade2 { get; set; }
        public virtual Servico Servico { get; set; }
        public virtual StatusAtividade StatusAtividade { get; set; }
        public virtual TipoAtividade TipoAtividade { get; set; }
        public virtual ICollection<AtividadeExecucao> AtividadeExecucaos { get; set; }
        public virtual ICollection<AtividadePrazo> AtividadePrazoes { get; set; }
        public virtual ICollection<LogAtividade> LogAtividades { get; set; }
        public virtual ICollection<RecursoEfetivo> RecursoEfetivoes { get; set; }
        public virtual Tecnologia Tecnologia { get; set; }
    }
}
