//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AtividadePrazo
    {
        public long atividadeId { get; set; }
        public long atividadePrazoId { get; set; }
        public Nullable<System.DateTime> dataEstimadaInicio { get; set; }
        public Nullable<System.DateTime> dataEstimadaFim { get; set; }
        public Nullable<int> prazoEstimadoConclusao { get; set; }
        public Nullable<long> atividadeIdDependencia { get; set; }
        public Nullable<long> usuarioIdEstimado { get; set; }
        public long usuarioIdInclusao { get; set; }
        public System.DateTime dataInclusao { get; set; }
    
        public virtual Atividade Atividade { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
