//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Contratoes = new HashSet<Contrato>();
            this.DocumentoExternoes = new HashSet<DocumentoExterno>();
        }
    
        public long clienteId { get; set; }
        public int codigo { get; set; }
        public string tipoCliente { get; set; }
        public string documentoIdentificacao { get; set; }
        public string nome { get; set; }
        public string identificadorGrupo { get; set; }
        public long empresaId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Contrato> Contratoes { get; set; }
        public virtual ICollection<DocumentoExterno> DocumentoExternoes { get; set; }
    }
}
