//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguradorObjeto
    {
        public long configuradorObjetoId { get; set; }
        public long configuradorOrdemServicoId { get; set; }
        public string Formulario { get; set; }
        public string Objeto { get; set; }
    
        public virtual ConfiguradorOrdemServico ConfiguradorOrdemServico { get; set; }
    }
}
