//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardChart
    {
        public int chartId { get; set; }
        public string chartTitle { get; set; }
        public string chartSubTitle { get; set; }
        public string chartProc { get; set; }
        public string chartType { get; set; }
        public string chartTask { get; set; }
        public Nullable<int> chartGroup { get; set; }
    }
}
