//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Despesa
    {
        public Despesa()
        {
            this.Reembolsoes = new HashSet<Reembolso>();
        }
    
        public long DespesaId { get; set; }
        public string Despesa1 { get; set; }
        public System.DateTime DataCriacao { get; set; }
    
        public virtual ICollection<Reembolso> Reembolsoes { get; set; }
    }
}
