//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNovoUsuario
    {
        public long emailNovoUsuarioId { get; set; }
        public string nome { get; set; }
        public Nullable<long> empresaId { get; set; }
        public string empresaNome { get; set; }
        public Nullable<long> cargoId { get; set; }
        public string cargoNome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<long> perfilId { get; set; }
        public string perfilNome { get; set; }
        public Nullable<long> grupoUsuarioId { get; set; }
        public string grupoUsuarioNome { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    }
}
