//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaseOrdemServico
    {
        public FaseOrdemServico()
        {
            this.StatusOrdemServicoes = new HashSet<StatusOrdemServico>();
        }
    
        public long faseOrdemServicoId { get; set; }
        public int sequenciaFaseOrdemServico { get; set; }
        public System.DateTime data { get; set; }
        public long faseId { get; set; }
        public long parecerId { get; set; }
        public Nullable<long> statusAtual { get; set; }
        public string observacao { get; set; }
        public long ordemId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Fase Fase { get; set; }
        public virtual Ordem Ordem { get; set; }
        public virtual Parecer Parecer { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual ICollection<StatusOrdemServico> StatusOrdemServicoes { get; set; }
    }
}
