//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Formulario
    {
        public long idFormulario { get; set; }
        public string email { get; set; }
        public bool confirmado { get; set; }
        public string formulario1 { get; set; }
        public string grupo { get; set; }
        public System.DateTime data { get; set; }
    }
}
