//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FraseKanban
    {
        public long fraseid { get; set; }
        public Nullable<long> projetoId { get; set; }
        public string frase { get; set; }
        public long usuarioIdInclusao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public System.DateTime dataInicio { get; set; }
        public System.DateTime dataFim { get; set; }
        public string ativo { get; set; }
    }
}
