//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hora
    {
        public long HoraId { get; set; }
        public long UsuarioId { get; set; }
        public long ProjetoId { get; set; }
        public System.DateTime dtLancamento { get; set; }
        public Nullable<System.DateTime> hrInicial { get; set; }
        public Nullable<System.DateTime> hrSaidaAlmoco { get; set; }
        public Nullable<System.DateTime> hrVoltaAlmoco { get; set; }
        public Nullable<System.DateTime> hrFinal { get; set; }
        public string dsTarefa { get; set; }
        public string Total { get; set; }
        public Nullable<short> Status { get; set; }
        public string Motivo { get; set; }
        public string Abonar { get; set; }
    }
}
