//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogOrdemServico
    {
        public LogOrdemServico()
        {
            this.Anexoes = new HashSet<Anexo>();
        }
    
        public long logOrdemServicoId { get; set; }
        public int sequenciaLogOrdemServico { get; set; }
        public long tipoEventoId { get; set; }
        public System.DateTime dataEvento { get; set; }
        public string apontamento { get; set; }
        public long usuarioId { get; set; }
        public Nullable<long> areaId { get; set; }
        public long ordemId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Anexo> Anexoes { get; set; }
        public virtual Area Area { get; set; }
        public virtual Ordem Ordem { get; set; }
        public virtual TipoEvento TipoEvento { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
