//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menu
    {
        public int IdMenu { get; set; }
        public string Menu1 { get; set; }
        public Nullable<int> IdMenuPai { get; set; }
        public string Url { get; set; }
        public Nullable<int> StatusCorrespondente { get; set; }
        public Nullable<byte> MostraContador { get; set; }
        public Nullable<int> Obrigatorio { get; set; }
        public string status { get; set; }
        public string Imagem { get; set; }
        public Nullable<int> Ordem { get; set; }
    }
}
