//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class GSMEntities : DbContext
    {
        public GSMEntities()
            : base("name=GSMEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<AditivoContrato> AditivoContratoes { get; set; }
        public DbSet<Anexo> Anexoes { get; set; }
        public DbSet<Aplicativo> Aplicativoes { get; set; }
        public DbSet<Area> Areas { get; set; }
        public DbSet<Atividade> Atividades { get; set; }
        public DbSet<AtividadeExecucao> AtividadeExecucaos { get; set; }
        public DbSet<AtividadePrazo> AtividadePrazoes { get; set; }
        public DbSet<bancoHora> bancoHoras { get; set; }
        public DbSet<Cargo> Cargoes { get; set; }
        public DbSet<Checklist> Checklists { get; set; }
        public DbSet<ClausulaContrato> ClausulaContratoes { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<ConfiguradorObjeto> ConfiguradorObjetoes { get; set; }
        public DbSet<ConfiguradorOrdemServico> ConfiguradorOrdemServicoes { get; set; }
        public DbSet<ConfiguradorProjetoUsuario> ConfiguradorProjetoUsuarios { get; set; }
        public DbSet<Contrato> Contratoes { get; set; }
        public DbSet<DashboardChart> DashboardCharts { get; set; }
        public DbSet<Despesa> Despesas { get; set; }
        public DbSet<DocumentoExterno> DocumentoExternoes { get; set; }
        public DbSet<DominiosValido> DominiosValidos { get; set; }
        public DbSet<Email> Emails { get; set; }
        public DbSet<EmailNovoUsuario> EmailNovoUsuarios { get; set; }
        public DbSet<Empresa> Empresas { get; set; }
        public DbSet<Fase> Fases { get; set; }
        public DbSet<FaseOrdemServico> FaseOrdemServicoes { get; set; }
        public DbSet<Feriado> Feriadoes { get; set; }
        public DbSet<Formulario> Formularios { get; set; }
        public DbSet<FraseKanban> FraseKanbans { get; set; }
        public DbSet<Funcionalidade> Funcionalidades { get; set; }
        public DbSet<GrupoUsuario> GrupoUsuarios { get; set; }
        public DbSet<Homologacao> Homologacaos { get; set; }
        public DbSet<Hora> Horas { get; set; }
        public DbSet<LogAtividade> LogAtividades { get; set; }
        public DbSet<LogOrdemServico> LogOrdemServicoes { get; set; }
        public DbSet<Notificacao> Notificacaos { get; set; }
        public DbSet<Ordem> Ordems { get; set; }
        public DbSet<ParametroContrato> ParametroContratoes { get; set; }
        public DbSet<Parecer> Parecers { get; set; }
        public DbSet<Perfil> Perfils { get; set; }
        public DbSet<Pergunta> Perguntas { get; set; }
        public DbSet<Ponto> Pontoes { get; set; }
        public DbSet<PrioridadeOrdemlog> PrioridadeOrdemlogs { get; set; }
        public DbSet<Projeto> Projetoes { get; set; }
        public DbSet<ProjetoAdministrativo> ProjetoAdministrativoes { get; set; }
        public DbSet<PropostaPrazo> PropostaPrazoes { get; set; }
        public DbSet<PropostaValor> PropostaValors { get; set; }
        public DbSet<Ramal> Ramals { get; set; }
        public DbSet<Recurso> Recursoes { get; set; }
        public DbSet<RecursoEfetivo> RecursoEfetivoes { get; set; }
        public DbSet<RecursoOrcado> RecursoOrcadoes { get; set; }
        public DbSet<Reembolso> Reembolsoes { get; set; }
        public DbSet<Servico> Servicoes { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<StatusAtividade> StatusAtividades { get; set; }
        public DbSet<StatusAtividadeExecucao> StatusAtividadeExecucaos { get; set; }
        public DbSet<StatusOrdemServico> StatusOrdemServicoes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<TblLog> TblLogs { get; set; }
        public DbSet<Tecnologia> Tecnologias { get; set; }
        public DbSet<Telefone> Telefones { get; set; }
        public DbSet<TipoAtividade> TipoAtividades { get; set; }
        public DbSet<TipoCriticidade> TipoCriticidades { get; set; }
        public DbSet<TipoEvento> TipoEventoes { get; set; }
        public DbSet<TipoNotificacao> TipoNotificacaos { get; set; }
        public DbSet<TipoOrdemServico> TipoOrdemServicoes { get; set; }
        public DbSet<TipoOrdemServicoPergunta> TipoOrdemServicoPerguntas { get; set; }
        public DbSet<TipoParecer> TipoParecers { get; set; }
        public DbSet<TipoServico> TipoServicoes { get; set; }
        public DbSet<TipoSituacao> TipoSituacaos { get; set; }
        public DbSet<Usuario> Usuarios { get; set; }
        public DbSet<ValorCobrar> ValorCobrars { get; set; }
        public DbSet<AplicativoOrdem> AplicativoOrdems { get; set; }
        public DbSet<AplicativoServico> AplicativoServicoes { get; set; }
        public DbSet<FuncionalidadeOrdem> FuncionalidadeOrdems { get; set; }
        public DbSet<FuncionalidadePerfil> FuncionalidadePerfils { get; set; }
        public DbSet<FuncionalidadeServico> FuncionalidadeServicoes { get; set; }
        public DbSet<Menu> Menus { get; set; }
        public DbSet<PerfilAcesso> PerfilAcessoes { get; set; }
        public DbSet<PrioridadeAlteracaoPrazo> PrioridadeAlteracaoPrazoes { get; set; }
        public DbSet<SASFEVEREIRO> SASFEVEREIROes { get; set; }
        public DbSet<TempRel> TempRels { get; set; }
        public DbSet<tvRanking> tvRankings { get; set; }
        public DbSet<UsuarioGrupoUsuario> UsuarioGrupoUsuarios { get; set; }
        public DbSet<UsuarioPerfil> UsuarioPerfils { get; set; }
    
        public virtual ObjectResult<Spr_Recursos_Selecionar_MVC_Result1> Spr_Recursos_Selecionar_MVC(Nullable<long> ordemId)
        {
            var ordemIdParameter = ordemId.HasValue ?
                new ObjectParameter("ordemId", ordemId) :
                new ObjectParameter("ordemId", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Spr_Recursos_Selecionar_MVC_Result1>("Spr_Recursos_Selecionar_MVC", ordemIdParameter);
        }
    
        public virtual ObjectResult<Spr_Atividades_Grupo_Result1> Spr_Atividades_Grupo(Nullable<long> userID)
        {
            var userIDParameter = userID.HasValue ?
                new ObjectParameter("userID", userID) :
                new ObjectParameter("userID", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Spr_Atividades_Grupo_Result1>("Spr_Atividades_Grupo", userIDParameter);
        }
    }
}
