//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notificacao
    {
        public long notificacaoId { get; set; }
        public int sequenciaNotificacao { get; set; }
        public long tipoNotificacaoId { get; set; }
        public System.DateTime dataEnvio { get; set; }
        public string destinatario { get; set; }
        public string mensagem { get; set; }
        public Nullable<long> parecerId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Parecer Parecer { get; set; }
        public virtual TipoNotificacao TipoNotificacao { get; set; }
    }
}
