//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordem
    {
        public Ordem()
        {
            this.Anexoes = new HashSet<Anexo>();
            this.ConfiguradorOrdemServicoes = new HashSet<ConfiguradorOrdemServico>();
            this.FaseOrdemServicoes = new HashSet<FaseOrdemServico>();
            this.Homologacaos = new HashSet<Homologacao>();
            this.LogOrdemServicoes = new HashSet<LogOrdemServico>();
            this.AplicativoOrdems = new HashSet<AplicativoOrdem>();
            this.FuncionalidadeOrdems = new HashSet<FuncionalidadeOrdem>();
            this.Parecers = new HashSet<Parecer>();
            this.PropostaPrazoes = new HashSet<PropostaPrazo>();
            this.PropostaValors = new HashSet<PropostaValor>();
            this.Servicoes = new HashSet<Servico>();
        }
    
        public long ordemId { get; set; }
        public string os { get; set; }
        public string assunto { get; set; }
        public System.DateTime dataOrdem { get; set; }
        public Nullable<System.DateTime> dataFimOrdem { get; set; }
        public Nullable<int> horasEfetivas { get; set; }
        public int prioridade { get; set; }
        public long projetoId { get; set; }
        public Nullable<long> funcionalidadeId { get; set; }
        public Nullable<long> responsavelExecutor { get; set; }
        public long tipoOrdemServicoId { get; set; }
        public Nullable<long> valorCobrarId { get; set; }
        public Nullable<long> documentoExternoId { get; set; }
        public string codigoDocumentoExterno { get; set; }
        public Nullable<long> faseAtual { get; set; }
        public Nullable<long> statusAtual { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
        public Nullable<short> faturamentoId { get; set; }
        public Nullable<System.DateTime> dataFaturamento { get; set; }
    
        public virtual ICollection<Anexo> Anexoes { get; set; }
        public virtual ICollection<ConfiguradorOrdemServico> ConfiguradorOrdemServicoes { get; set; }
        public virtual DocumentoExterno DocumentoExterno { get; set; }
        public virtual Fase Fase { get; set; }
        public virtual ICollection<FaseOrdemServico> FaseOrdemServicoes { get; set; }
        public virtual ICollection<Homologacao> Homologacaos { get; set; }
        public virtual ICollection<LogOrdemServico> LogOrdemServicoes { get; set; }
        public virtual ICollection<AplicativoOrdem> AplicativoOrdems { get; set; }
        public virtual ICollection<FuncionalidadeOrdem> FuncionalidadeOrdems { get; set; }
        public virtual Projeto Projeto { get; set; }
        public virtual Status Status1 { get; set; }
        public virtual TipoOrdemServico TipoOrdemServico { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        public virtual Usuario Usuario2 { get; set; }
        public virtual ValorCobrar ValorCobrar { get; set; }
        public virtual ICollection<Parecer> Parecers { get; set; }
        public virtual ICollection<PropostaPrazo> PropostaPrazoes { get; set; }
        public virtual ICollection<PropostaValor> PropostaValors { get; set; }
        public virtual ICollection<Servico> Servicoes { get; set; }
    }
}
