//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParametroContrato
    {
        public long parametroContratoId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public long tipoCriticidadeId { get; set; }
        public Nullable<long> tipoServicoId { get; set; }
        public Nullable<double> proporcaoSLA { get; set; }
        public string expressaoCalculo { get; set; }
        public string regra { get; set; }
        public Nullable<long> aditivoContratoId { get; set; }
        public Nullable<long> contratoId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
        public bool BaseLine { get; set; }
        public Nullable<decimal> ValorTotal { get; set; }
    
        public virtual AditivoContrato AditivoContrato { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual TipoCriticidade TipoCriticidade { get; set; }
        public virtual TipoServico TipoServico { get; set; }
    }
}
