//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parecer
    {
        public Parecer()
        {
            this.Anexoes = new HashSet<Anexo>();
            this.FaseOrdemServicoes = new HashSet<FaseOrdemServico>();
            this.Notificacaos = new HashSet<Notificacao>();
            this.StatusOrdemServicoes = new HashSet<StatusOrdemServico>();
        }
    
        public long parecerId { get; set; }
        public int sequenciaParecer { get; set; }
        public System.DateTime dataParecer { get; set; }
        public Nullable<long> areaId { get; set; }
        public string parecer1 { get; set; }
        public long tipoParecerId { get; set; }
        public Nullable<long> ordemId { get; set; }
        public long usuarioId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Anexo> Anexoes { get; set; }
        public virtual Area Area { get; set; }
        public virtual ICollection<FaseOrdemServico> FaseOrdemServicoes { get; set; }
        public virtual ICollection<Notificacao> Notificacaos { get; set; }
        public virtual Ordem Ordem { get; set; }
        public virtual TipoParecer TipoParecer { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<StatusOrdemServico> StatusOrdemServicoes { get; set; }
    }
}
