//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Perfil
    {
        public Perfil()
        {
            this.Checklists = new HashSet<Checklist>();
            this.PerfilAcessoes = new HashSet<PerfilAcesso>();
            this.Perguntas = new HashSet<Pergunta>();
            this.UsuarioPerfils = new HashSet<UsuarioPerfil>();
        }
    
        public long perfilId { get; set; }
        public long empresaId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public bool admin { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<PerfilAcesso> PerfilAcessoes { get; set; }
        public virtual ICollection<Pergunta> Perguntas { get; set; }
        public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; }
    }
}
