//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pergunta
    {
        public Pergunta()
        {
            this.Checklists = new HashSet<Checklist>();
        }
    
        public long perguntaId { get; set; }
        public string pergunta1 { get; set; }
        public long tipoAtividadeId { get; set; }
        public long perfilId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual TipoAtividade TipoAtividade { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual Usuario Usuario1 { get; set; }
    }
}
