//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ponto
    {
        public long pontoId { get; set; }
        public Nullable<System.DateTime> dataIni { get; set; }
        public Nullable<System.DateTime> dataFim { get; set; }
        public string ip { get; set; }
        public string dominio { get; set; }
        public string maquina { get; set; }
        public string macAddressLocal { get; set; }
        public string macAddressWifi { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    }
}
