//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrioridadeAlteracaoPrazo
    {
        public Nullable<System.Guid> prioridadeAlteracaoId { get; set; }
        public Nullable<byte> prioridadeAlteracaoTipo { get; set; }
        public Nullable<long> demandaId { get; set; }
        public Nullable<long> demandaPrazoId { get; set; }
        public string demandaAssunto { get; set; }
        public Nullable<System.DateTime> dataDemanda { get; set; }
        public Nullable<System.DateTime> dataEstimadaInicio { get; set; }
        public Nullable<System.DateTime> dataEstimadaFim { get; set; }
        public Nullable<int> prazoEstimadoConclusao { get; set; }
        public Nullable<long> demandaIdDependencia { get; set; }
        public Nullable<long> usuarioIdEstimado { get; set; }
        public Nullable<System.DateTime> dtAlteracao { get; set; }
        public long GrupoUsuarioId { get; set; }
    }
}
