//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Projeto
    {
        public Projeto()
        {
            this.Aplicativoes = new HashSet<Aplicativo>();
            this.ConfiguradorOrdemServicoes = new HashSet<ConfiguradorOrdemServico>();
            this.ConfiguradorProjetoUsuarios = new HashSet<ConfiguradorProjetoUsuario>();
            this.Ordems = new HashSet<Ordem>();
            this.Reembolsoes = new HashSet<Reembolso>();
            this.ProjetoAdministrativoes = new HashSet<ProjetoAdministrativo>();
            this.Tecnologias = new HashSet<Tecnologia>();
        }
    
        public long projetoId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public string sigla { get; set; }
        public Nullable<long> aditivoContratoId { get; set; }
        public Nullable<long> contratoId { get; set; }
        public long tipoSituacaoId { get; set; }
        public Nullable<long> ProjectLead { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual AditivoContrato AditivoContrato { get; set; }
        public virtual ICollection<Aplicativo> Aplicativoes { get; set; }
        public virtual ICollection<ConfiguradorOrdemServico> ConfiguradorOrdemServicoes { get; set; }
        public virtual ICollection<ConfiguradorProjetoUsuario> ConfiguradorProjetoUsuarios { get; set; }
        public virtual Contrato Contrato { get; set; }
        public virtual ICollection<Ordem> Ordems { get; set; }
        public virtual ICollection<Reembolso> Reembolsoes { get; set; }
        public virtual TipoSituacao TipoSituacao { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<ProjetoAdministrativo> ProjetoAdministrativoes { get; set; }
        public virtual ICollection<Tecnologia> Tecnologias { get; set; }
    }
}
