//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropostaPrazo
    {
        public long propostaPrazoId { get; set; }
        public int sequenciaPropostaPrazo { get; set; }
        public Nullable<System.DateTime> dataEstimadaInicio { get; set; }
        public Nullable<System.DateTime> dataEstimadaFim { get; set; }
        public Nullable<int> prazoEstimadoConclusao { get; set; }
        public long ordemId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual Ordem Ordem { get; set; }
    }
}
