//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recurso
    {
        public Recurso()
        {
            this.LogAtividades = new HashSet<LogAtividade>();
            this.Recurso1 = new HashSet<Recurso>();
            this.RecursoEfetivoes = new HashSet<RecursoEfetivo>();
            this.RecursoOrcadoes = new HashSet<RecursoOrcado>();
        }
    
        public long recursoId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public string tipoRecurso { get; set; }
        public Nullable<decimal> custo { get; set; }
        public Nullable<long> recursoRelacionado { get; set; }
        public Nullable<long> tipoAtividadeId { get; set; }
        public Nullable<long> usuarioId { get; set; }
        public string observacao { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<LogAtividade> LogAtividades { get; set; }
        public virtual ICollection<Recurso> Recurso1 { get; set; }
        public virtual Recurso Recurso2 { get; set; }
        public virtual TipoAtividade TipoAtividade { get; set; }
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<RecursoEfetivo> RecursoEfetivoes { get; set; }
        public virtual ICollection<RecursoOrcado> RecursoOrcadoes { get; set; }
    }
}
