//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SASFEVEREIRO
    {
        public string Descrição_da_Rotina { get; set; }
        public string Responsável { get; set; }
        public string C1 { get; set; }
        public Nullable<double> C2 { get; set; }
        public Nullable<double> C3 { get; set; }
        public Nullable<double> C4 { get; set; }
        public Nullable<double> C5 { get; set; }
        public Nullable<double> C6 { get; set; }
        public string C7 { get; set; }
        public string C8 { get; set; }
        public Nullable<double> C9 { get; set; }
        public Nullable<double> C10 { get; set; }
        public Nullable<double> C11 { get; set; }
        public Nullable<double> C12 { get; set; }
        public Nullable<double> C13 { get; set; }
        public string C14 { get; set; }
        public string C15 { get; set; }
        public Nullable<double> C16 { get; set; }
        public string C17 { get; set; }
        public Nullable<double> C18 { get; set; }
        public Nullable<double> C19 { get; set; }
        public Nullable<double> C20 { get; set; }
        public string C21 { get; set; }
        public string C22 { get; set; }
        public Nullable<double> C23 { get; set; }
        public Nullable<double> C24 { get; set; }
        public Nullable<double> C25 { get; set; }
        public Nullable<double> C26 { get; set; }
        public Nullable<double> C27 { get; set; }
        public string C28 { get; set; }
        public Nullable<double> Qtd { get; set; }
        public Nullable<double> Horas { get; set; }
        public Nullable<double> Qtdxhoras { get; set; }
        public int id { get; set; }
    }
}
