//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Servico
    {
        public Servico()
        {
            this.Anexoes = new HashSet<Anexo>();
            this.Atividades = new HashSet<Atividade>();
            this.AplicativoServicoes = new HashSet<AplicativoServico>();
            this.FuncionalidadeServicoes = new HashSet<FuncionalidadeServico>();
        }
    
        public long servicoId { get; set; }
        public int sequenciaServico { get; set; }
        public string nome { get; set; }
        public Nullable<int> prioridade { get; set; }
        public Nullable<long> tipoServicoId { get; set; }
        public Nullable<System.DateTime> dataServico { get; set; }
        public Nullable<int> previsaoHorasExecucao { get; set; }
        public Nullable<decimal> valorEstipulado { get; set; }
        public Nullable<bool> atenderSLA { get; set; }
        public long ordemId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
        public string Descricao { get; set; }
        public Nullable<long> GrupoUsuarioId { get; set; }
        public Nullable<long> subservicoRelacionado { get; set; }
        public Nullable<long> tecnologiaId { get; set; }
    
        public virtual ICollection<Anexo> Anexoes { get; set; }
        public virtual ICollection<Atividade> Atividades { get; set; }
        public virtual Ordem Ordem { get; set; }
        public virtual ICollection<AplicativoServico> AplicativoServicoes { get; set; }
        public virtual ICollection<FuncionalidadeServico> FuncionalidadeServicoes { get; set; }
        public virtual TipoServico TipoServico { get; set; }
        public virtual Servico Servico1 { get; set; }
        public virtual Servico Servico2 { get; set; }
        public virtual Tecnologia Tecnologia { get; set; }
    }
}
