//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusOrdemServico
    {
        public long statusOrdemServicoId { get; set; }
        public int sequenciaStatusOrdemServico { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public long statusId { get; set; }
        public long parecerRelacionado { get; set; }
        public string observacao { get; set; }
        public long faseOrdemServicoId { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual FaseOrdemServico FaseOrdemServico { get; set; }
        public virtual Parecer Parecer { get; set; }
        public virtual Status Status1 { get; set; }
    }
}
