//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusAtividadeExecucao
    {
        public StatusAtividadeExecucao()
        {
            this.AtividadeExecucaos = new HashSet<AtividadeExecucao>();
        }
    
        public long StatusAtividadeExecucaoId { get; set; }
        public Nullable<long> StatusAtividadeId { get; set; }
        public string nome { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<AtividadeExecucao> AtividadeExecucaos { get; set; }
        public virtual StatusAtividade StatusAtividade { get; set; }
    }
}
