//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Status
    {
        public Status()
        {
            this.ConfiguradorOrdemServicoes = new HashSet<ConfiguradorOrdemServico>();
            this.FaseOrdemServicoes = new HashSet<FaseOrdemServico>();
            this.Ordems = new HashSet<Ordem>();
            this.StatusOrdemServicoes = new HashSet<StatusOrdemServico>();
        }
    
        public long statusId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status1 { get; set; }
    
        public virtual ICollection<ConfiguradorOrdemServico> ConfiguradorOrdemServicoes { get; set; }
        public virtual ICollection<FaseOrdemServico> FaseOrdemServicoes { get; set; }
        public virtual ICollection<Ordem> Ordems { get; set; }
        public virtual ICollection<StatusOrdemServico> StatusOrdemServicoes { get; set; }
    }
}
