//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempRel
    {
        public string Nome { get; set; }
        public string Projeto { get; set; }
        public string Servico { get; set; }
        public string Atividade { get; set; }
        public Nullable<int> HorasEstimadas { get; set; }
        public string HorasPrevistaDia { get; set; }
        public string DataEstimadaInicio { get; set; }
        public string DataEstimadaFim { get; set; }
        public Nullable<int> D2014_January_1 { get; set; }
        public Nullable<int> D2014_May_30 { get; set; }
        public Nullable<int> TotalHorasExecutadas { get; set; }
    }
}
