//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAtividade
    {
        public TipoAtividade()
        {
            this.Atividades = new HashSet<Atividade>();
            this.Perguntas = new HashSet<Pergunta>();
            this.Recursoes = new HashSet<Recurso>();
        }
    
        public long tipoAtividadeId { get; set; }
        public int codigo { get; set; }
        public string nome { get; set; }
        public Nullable<int> tempoEstimado { get; set; }
        public bool valorada { get; set; }
        public Nullable<decimal> valorEstimado { get; set; }
        public string criterioCobranca { get; set; }
        public string observacao { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Atividade> Atividades { get; set; }
        public virtual ICollection<Pergunta> Perguntas { get; set; }
        public virtual ICollection<Recurso> Recursoes { get; set; }
    }
}
