//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        public Usuario()
        {
            this.AtividadePrazoes = new HashSet<AtividadePrazo>();
            this.Checklists = new HashSet<Checklist>();
            this.Checklists1 = new HashSet<Checklist>();
            this.ConfiguradorOrdemServicoes = new HashSet<ConfiguradorOrdemServico>();
            this.ConfiguradorOrdemServicoes1 = new HashSet<ConfiguradorOrdemServico>();
            this.ConfiguradorProjetoUsuarios = new HashSet<ConfiguradorProjetoUsuario>();
            this.Emails = new HashSet<Email>();
            this.Homologacaos = new HashSet<Homologacao>();
            this.Homologacaos1 = new HashSet<Homologacao>();
            this.LogOrdemServicoes = new HashSet<LogOrdemServico>();
            this.Ordems = new HashSet<Ordem>();
            this.Ordems1 = new HashSet<Ordem>();
            this.Ordems2 = new HashSet<Ordem>();
            this.Parecers = new HashSet<Parecer>();
            this.Perguntas = new HashSet<Pergunta>();
            this.Perguntas1 = new HashSet<Pergunta>();
            this.Projetoes = new HashSet<Projeto>();
            this.ProjetoAdministrativoes = new HashSet<ProjetoAdministrativo>();
            this.Ramals = new HashSet<Ramal>();
            this.Recursoes = new HashSet<Recurso>();
            this.Reembolsoes = new HashSet<Reembolso>();
            this.Telefones = new HashSet<Telefone>();
            this.UsuarioGrupoUsuarios = new HashSet<UsuarioGrupoUsuario>();
            this.UsuarioPerfils = new HashSet<UsuarioPerfil>();
            this.Tecnologias = new HashSet<Tecnologia>();
        }
    
        public long usuarioId { get; set; }
        public Nullable<long> cargoId { get; set; }
        public Nullable<long> empresaId { get; set; }
        public string login { get; set; }
        public string nome { get; set; }
        public string senha { get; set; }
        public string email { get; set; }
        public bool autenticaDominio { get; set; }
        public bool senhaExpira { get; set; }
        public Nullable<int> qtdDiasExpiracao { get; set; }
        public Nullable<System.DateTime> dataAniversario { get; set; }
        public string foto { get; set; }
        public Nullable<long> usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public Nullable<System.DateTime> ultimoAcesso { get; set; }
        public string status { get; set; }
        public string telefone { get; set; }
        public string macAddressLocal { get; set; }
        public string macAddressWifi { get; set; }
    
        public virtual ICollection<AtividadePrazo> AtividadePrazoes { get; set; }
        public virtual Cargo Cargo { get; set; }
        public virtual ICollection<Checklist> Checklists { get; set; }
        public virtual ICollection<Checklist> Checklists1 { get; set; }
        public virtual ICollection<ConfiguradorOrdemServico> ConfiguradorOrdemServicoes { get; set; }
        public virtual ICollection<ConfiguradorOrdemServico> ConfiguradorOrdemServicoes1 { get; set; }
        public virtual ICollection<ConfiguradorProjetoUsuario> ConfiguradorProjetoUsuarios { get; set; }
        public virtual ICollection<Email> Emails { get; set; }
        public virtual Empresa Empresa { get; set; }
        public virtual ICollection<Homologacao> Homologacaos { get; set; }
        public virtual ICollection<Homologacao> Homologacaos1 { get; set; }
        public virtual ICollection<LogOrdemServico> LogOrdemServicoes { get; set; }
        public virtual ICollection<Ordem> Ordems { get; set; }
        public virtual ICollection<Ordem> Ordems1 { get; set; }
        public virtual ICollection<Ordem> Ordems2 { get; set; }
        public virtual ICollection<Parecer> Parecers { get; set; }
        public virtual ICollection<Pergunta> Perguntas { get; set; }
        public virtual ICollection<Pergunta> Perguntas1 { get; set; }
        public virtual ICollection<Projeto> Projetoes { get; set; }
        public virtual ICollection<ProjetoAdministrativo> ProjetoAdministrativoes { get; set; }
        public virtual ICollection<Ramal> Ramals { get; set; }
        public virtual ICollection<Recurso> Recursoes { get; set; }
        public virtual ICollection<Reembolso> Reembolsoes { get; set; }
        public virtual ICollection<Telefone> Telefones { get; set; }
        public virtual ICollection<UsuarioGrupoUsuario> UsuarioGrupoUsuarios { get; set; }
        public virtual ICollection<UsuarioPerfil> UsuarioPerfils { get; set; }
        public virtual ICollection<Tecnologia> Tecnologias { get; set; }
    }
}
