//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GServiceManagerMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ValorCobrar
    {
        public ValorCobrar()
        {
            this.Ordems = new HashSet<Ordem>();
        }
    
        public long valorCobrarId { get; set; }
        public System.DateTime dataLancamento { get; set; }
        public Nullable<decimal> valorTotal { get; set; }
        public Nullable<double> desconto { get; set; }
        public Nullable<decimal> acrescimo { get; set; }
        public Nullable<decimal> valorFinal { get; set; }
        public Nullable<int> totalConsumido { get; set; }
        public long usuarioIdInclusao { get; set; }
        public Nullable<long> usuarioIdAlteracao { get; set; }
        public System.DateTime dataInclusao { get; set; }
        public Nullable<System.DateTime> dataAlteracao { get; set; }
        public string status { get; set; }
    
        public virtual ICollection<Ordem> Ordems { get; set; }
    }
}
